name: Test supported versions
on:
  push:
    branches:
      - 'master'
  pull_request: {}

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/rails_6_1.gemfile
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: 3.1

      - name: Run linters
        run: bundle exec rubocop

  spec:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.0", 3.1, 3.2, 3.3, 3.4]
        gemfile: [rails_6_1, rails_7_0, rails_7_1, rails_7_2, rails_8_0]
        exclude:
          # Rails < 7.0.1 is not compatible with Ruby 3.1+, and Rails 7.2 requires Ruby >= 3.1
          - ruby: 3.1
            gemfile: rails_6_1
          - ruby: 3.2
            gemfile: rails_6_1
          - ruby: 3.0
            gemfile: rails_7_2
          - ruby: 3.0
            gemfile: rails_8_0
          - ruby: 3.1
            gemfile: rails_8_0
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/${{ matrix.gemfile }}.gemfile
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ${{ matrix.ruby }}
          rubygems: 3.5.18

      - name: Migrate DB
        run: bundle exec rake app:db:migrate

      - name: Prepare DB
        run: bundle exec rake app:db:test:prepare

      - name: Install ImageMagick
        run: sudo apt-get update && sudo apt-get install -y imagemagick

      - name: Run spec
        run: bundle exec rspec
