name: Test upcoming versions
on:
  push:
    branches:
      - 'master'
  pull_request: {}

jobs:
  spec:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: 3.4
            gemfile: rails_edge
          - ruby: head
            gemfile: rails_8_0
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/${{ matrix.gemfile }}.gemfile
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ${{ matrix.ruby }}

      - name: Migrate DB
        run: bundle exec rake app:db:migrate

      - name: Prepare DB
        run: bundle exec rake app:db:test:prepare

      - name: Install ImageMagick
        run: sudo apt-get update && sudo apt-get install -y imagemagick

      - name: Run spec
        run: bundle exec rspec
